dataset:
  name: CIC-IDS2017
  format: traffic_2d_flow
  dataset_root: /home/xx
  train_data_dir: /Traindata
  train_label_dir: /Trainlabel
  valid_data_dir: None
  valid_label_dir: None
  test_data_dir: /Testdat
  test_label_dir: /Testlabel
  flow_num: 8
  train_batch_size: 128
  test_batch_size: 128
  inference_batch_size: 128
  num_workers: 1
  task: classification
  test_split_mode: from_dir
  image_size:
  - 40
  - 40
  val_split_mode: same_as_test
  eval_batch_size: 128

model:
  name: undiff
  latent_vec_size: 128
  n_features: 32
  early_stopping:
    patience: 6
    metric: image_AUROC
    mode: max
  lr: 5.0e-05`
  beta1: 0.5
  beta2: 0.999
  wrec: 0.5
  wnig: 0.005
  wpenal: 1.0e-05
  warmup: 0
  normalization_method: none
  input_size:
  - 40
  - 40
metrics:
  image:
  - F1Score
  - AUROC
  - Accuracy
  - Precision
  - Recall
  threshold:
    method: adaptive
    manual_image: null
visualization:
  show_images: false
  save_images: false
  log_images: false
  image_save_path: null
  mode: full
project:
  seed: 42
  path: results
  unique_dir: false
logging:
  logger:
  - csv
  log_graph: false
optimization:
  export_mode: null
trainer:
  enable_checkpointing: true
  default_root_dir: results
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices:
  - 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 50
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 50
  accelerator: auto
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
